/**
 * UI Components Index
 * This file exports all UI components for easy imports throughout the application
 * Using Australian English spelling as per preferences
 */

// Base UI components
export { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "./accordion"
export { Alert, AlertDescription, AlertTitle } from "./alert"
export { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "./alert-dialog"
export { AspectRatio } from "./aspect-ratio"
export { Avatar, AvatarFallback, AvatarImage } from "./avatar"
export { AvatarGroup } from "./avatar-group"
export { Button, ButtonVariants } from "./button"
export { Calendar } from "./calendar"
export { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "./card"
export { Checkbox } from "./checkbox"
export { ClientCard } from "./client-card"
export { Collapsible, CollapsibleContent, CollapsibleTrigger } from "./collapsible"
export { Command, CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList, CommandSeparator, CommandShortcut } from "./command"
export { ConfirmDialog } from "./confirm-dialog"
export { ContextMenu, ContextMenuCheckboxItem, ContextMenuContent, ContextMenuGroup, ContextMenuItem, ContextMenuLabel, ContextMenuPortal, ContextMenuRadioGroup, ContextMenuRadioItem, ContextMenuSeparator, ContextMenuShortcut, ContextMenuSub, ContextMenuSubContent, ContextMenuSubTrigger, ContextMenuTrigger } from "./context-menu"
export { CustomDialog } from "./custom-dialog"
export { DatePicker } from "./date-picker"
export { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "./dialog"
export { DropdownMenu, DropdownMenuCheckboxItem, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem, DropdownMenuLabel, DropdownMenuPortal, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator, DropdownMenuShortcut, DropdownMenuSub, DropdownMenuSubContent, DropdownMenuSubTrigger, DropdownMenuTrigger } from "./dropdown-menu"
export { EditPayrollDialog } from "./edit-payroll-dialog"
export { FormField } from "./form-field"
export { FormLayout } from "./form-layout"
export { GenerateMissingDatesButton } from "./generate-missing-dates-button"
export { HoverCard, HoverCardContent, HoverCardTrigger } from "./hover-card"
export { Input } from "./input"
export { Label } from "./label"
export { Menubar, MenubarCheckboxItem, MenubarContent, MenubarGroup, MenubarItem, MenubarLabel, MenubarMenu, MenubarPortal, MenubarRadioGroup, MenubarRadioItem, MenubarSeparator, MenubarShortcut, MenubarSub, MenubarSubContent, MenubarSubTrigger, MenubarTrigger } from "./menubar"
export { Modal } from "./modal"
export { default as ModalForm } from "./modal-form"
export { NavigationMenu, NavigationMenuContent, NavigationMenuItem, NavigationMenuLink, NavigationMenuList, NavigationMenuTrigger, navigationMenuTriggerStyle } from "./navigation-menu"
export { NotesModal } from "./notes-modal"
export { PayrollDetailsCard } from "./payroll-details-card"
export { PayrollListCard } from "./payroll-list-card"
export { Popover, PopoverContent, PopoverTrigger } from "./popover"
export { Progress } from "./progress"
export { RadioGroup, RadioGroupItem } from "./radio-group"
export { RefreshButton } from "./refresh-button"
export { ResizableHandle, ResizablePanel, ResizablePanelGroup } from "./resizable"
export { ScrollArea, ScrollBar } from "./scroll-area"
export { SectionCard } from "./section-card"
export { Select, SelectContent, SelectGroup, SelectItem, SelectLabel, SelectSeparator, SelectTrigger, SelectValue } from "./select"
export { Separator } from "./separator"
export { Sheet, SheetClose, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle, SheetTrigger } from "./sheet"
export { Skeleton } from "./skeleton"
export { Slider } from "./slider"
export { Toaster } from "./sonner"
export { Spinner } from "./spinner"
export { Switch } from "./switch"
export { Table, TableBody, TableCaption, TableCell, TableFooter, TableHead, TableHeader, TableRow } from "./table"
export { Tabs, TabsContent, TabsList, TabsTrigger } from "./tabs"
export { Textarea } from "./textarea"
export { ThemeToggle } from "./theme-toggle"
export { Toast } from "./toast"
export { Toggle, toggleVariants } from "./toggle"
export { ToggleGroup, ToggleGroupItem } from "./toggle-group"
export { Toolbar, ToolbarButton, ToolbarLink, ToolbarSeparator, ToolbarToggleGroup, ToolbarToggleItem } from "./toolbar"
export { UrgentAlerts } from "./urgent-alerts"

// Charts export
export * from "./chart"