/**
 * fragments - Barrel file
 * Generated by enhanced-cleanup script
 */

export * from './WorkScheduleFragment.generated'
export * from './StaffManagerFragment.generated'
export * from './StaffLeaveFragment.generated'
export * from './StaffFragment.generated'
export * from './PayrollFragment.generated'
export * from './PayrollDetailFragment.generated'
export * from './PayrollDateTypeFragment.generated'
export * from './PayrollDateFragment.generated'
export * from './PayrollCycleFragment.generated'
export * from './NoteFragment.generated'
export * from './LeaveFragment.generated'
export * from './HolidayFragment.generated'
export * from './FeatureFlagFragment.generated'
export * from './ExternalSystemFragment.generated'
export * from './ClientFragment.generated'
export * from './ClientExternalSystemFragment.generated'
export * from './AppSettingsFragment.generated'
export * from './AdjustmentRuleFragment.generated'
